spring:
  application:
    name: airbnb

  # h2 console
  h2:
    console:
      enabled: true
      path: /h2-console

  # datasource - h2 (for test)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/airbnb
    username: sa
    password:

  # ddl-auto
  jpa:
    hibernate:
      ddl-auto: create # create create-drop update validate none(default/ on production)

    properties:
      hibernate:
        show_sql: true
        format_sql: true

    # data.sql operate after hibernate init (not on production)
    defer-datasource-initialization: true

  # sql init (not on production)
  sql:
    init:
      mode: always

# Logging level
logging:
  level:
    com:
      airbnb: debug

# url prefix
server:
  servlet:
    context-path: /api/v1

pwd:
  encrypt:
    secret-key: