spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23licEiwb7WgUnlhjc
            client-secret: 79945e4b3e81c30397a4ef5985bca30b8c0f2dab
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            scope: name,email,avatar_url
#          google:
#            client-id:
#            client-secret:
#            scope: profile,email
#            redirect-uri:
#          naver:
#            client-id:
#            client-secret:
#            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
#            scope: name,email,profile_image
#            client-authentication-method: client_secret_post
#            authorization_grant_type: authorization_code
#            client-name: Naver
#          kakao:
#            client-id:
#            client-secret:
#            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
#            scope: profile_nickname,profile_image,account_email
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            client-name: Kakao
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-info-authentication-method: header
            user-name-attribute: email
#          google:
#            authorization-uri:
#            token-uri: https://www.googleapis.com/oauth2/v4/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            user-info-authentication-method: header
#            user-name-attribute:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-info-authentication-method: header
#            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-info-authentication-method: header
#            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정